### ISSUE TITLE
TypeError during startup

### ISSUE THREAD

**Issue by grajkiran** [grajkiran/ezeplot#1]
Traceback (most recent call last):
  File "**main**.py", line 67, in <module>
    app = AppWindow(root, system, blit = opts.blit, icon = icon)#, embedded = opts.embed)
  File "gui.py", line 93, in **init**
    self.controls = self._add_widgets(cframe)
  File "gui.py", line 550, in _add_widgets
    frame.rowconfigure(f_update.grid_info()['row'], weight = 1)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2000, in grid_info
    self.tk.call('grid', 'info', self._w))
TypeError: coercing to Unicode: need string or buffer, _tkinter.Tcl_Obj found

**Comment by grajkiran** [comment]
('python:', '2.7.6')
('matplotlib:', '1.3.1')
('numpy:', '1.8.2')
('scipy:', '0.13.3')
